### ISSUE TITLE
Is it possible to make the QR code smaller?

### ISSUE THREAD

**Issue by fdverwoerd** [danielgjackson/qrcodejs#1]
Is it possible to make the QR code smaller?

I am using this repository to render QR codes containing VCARD text blobs.

But because that becomes alot of text the QR code becomes bigger. Is there a way to render it smaller using the options? 

I've read output size somewhere but could not find example.

Kind regards,

Rick

Code for reference

```typescript
import QrCode from "../functions/qrcode";
/**
 * vCard logic for human
 *
 * @see: https://github.com/danielgjackson/qrcodejs
 */
function vcardInit(scope: Document | HTMLElement): void {
  const body = scope.querySelector("body")!;
  console.log(body, QrCode);

  const vcard = document.getElementById("vcard")!;
  const data = vcard.textContent;
  const matrix = QrCode.generate(data);
  const uri = QrCode.render("svg-uri", matrix, {});
  document.querySelector('#qrcode_holder').src = uri;

  // Create a Blob containing the vCard content
  const blob = new Blob([data], { type: "text/vcard" });
  // const blob = new Blob([data], { type: "application/octet-stream" });

  // Extract the page title
  const pageTitle = document.title;

  // Replace spaces with hyphens and convert to lowercase
  const filename = pageTitle.replace(/\s+/g, '-').toLowerCase();

  // Create a download link
  const downloadLink = document.createElement("a");
  downloadLink.href = URL.createObjectURL(blob);
  downloadLink.innerHTML = `<svg><use href="#svg_carret"></use></svg><span>Download vCard</span>`;
  downloadLink.classList.add("button", "arrow");
  downloadLink.download = `${filename}.vcf`; // Specify the filename

  // Append the download link to the document and trigger the click event
  vcard.parentElement.querySelector(".button-group").prepend(downloadLink);

  // Clean up
  // document.body.removeChild(downloadLink);

}
```

**Comment by danielgjackson** [comment]
The first thing to try would be to pass a second, `options`, parameter to `generate()`, specifying `errorCorrectionLevel = 0`, i.e. `QrCode.generate(data, { errorCorrectionLevel: 0; })` -- this will make the code a little less tolerant to errors, but will simplify it.

The most effect way of making a smaller code is to simply reduce the amount of data you're giving it.  I would look at the raw text of the vCard, and see if there are any opportunities to reduce the number of characters.  

Finally, the only other thing to try would be to encode specific "segments" of text as minimally as possible.  This is because QR Codes can encode a "segment" of: all numbers really efficiently; mixed all-caps/numeric/limited puncutation (`"$%*+-./: "`) quite efficiently; and full-blown 8-bit UTF-encoded text least efficiently.  However, there is some overhead in switching between segments, so it's not always easy to know the most efficient method.   To make use of this, pass in an array of strings, one for each segment -- but beware that it will not autmatically merge same-encoded segments, so you should be sure each segment will be differently encoded to not add to the overhead.  An example would be: `QrCode.generate(["TESTING-", "1234567890", "!!!"], { errorCorrectionLevel: 0; })`
